Environment: "dev"

PROJECT:
  NAME: "go-back-template-hackathon"
  VERSION: "1.0.0"
  DESCRIPTION: "Go back-end project"
  DOCKER_NETWORK: "go-back-temp-hack-net"

SERVER:
  PORT: "3000"
  HOST: "0.0.0.0"
  DOCKER_PORT: "8070"

DB:
  HOST: "localhost"
  PORT: "5436"
  NAME: "postgres"
  USER: "postgres"
  SSLMODE: "disable"